#!/usr/bin/env python3
"""
split_samples.py — Generate an 80/20 train/val split at the sample level.

Reads the Stage 2 merged CSV, finds all unique sample IDs that carry ASCAT
ground truth (nMajor + nMinor non-null), and splits them 80% calibration /
20% validation by sample (not by segment) so no sample leaks across sets.

Outputs (written to autoresearch_baf_hrd/):
    calibration_samples.txt   — sample IDs to use in calibrate_thresholds.py
    validation_samples.txt    — sample IDs to use in prepare.py / experiment.py

The split is deterministic (RANDOM_STATE = 42).  Re-running produces the same
files unless the input data changes.

Usage:
    python split_samples.py
    # or via sbatch:
    sbatch run_split_samples.sbatch
"""

import os
import numpy as np
import pandas as pd

# ============================================================
# CONFIGURATION
# ============================================================

MERGED_CSV = (
    "/storage/scratch01/groups/co/cn_extra/alleleSpecific/tso_samples/20260406"
    "/merged_segments_baf_metrics_ALL_with20bins_enhancedFeatures.csv"
)

OUT_DIR = os.path.join(os.path.dirname(__file__), "autoresearch_baf_hrd")

CAL_FRAC     = 0.80   # fraction of samples used for calibration
RANDOM_STATE = 42

# ============================================================
# MAIN
# ============================================================

def main():
    print("=" * 60)
    print("SAMPLE-LEVEL TRAIN / VALIDATION SPLIT")
    print("=" * 60)

    if not os.path.exists(MERGED_CSV):
        raise FileNotFoundError(f"Merged CSV not found: {MERGED_CSV}")

    print(f"Loading: {MERGED_CSV}")
    # Only need a few columns to identify ASCAT samples
    df = pd.read_csv(MERGED_CSV, usecols=lambda c: c in (
        'sample', 'SampleID', 'sample_name', 'nMajor', 'nMinor',
        'nMajor_true', 'nMinor_true'
    ))
    print(f"  {len(df):,} rows loaded")

    # Identify the sample column
    sample_col = next(
        (c for c in ('sample', 'SampleID', 'sample_name') if c in df.columns),
        None
    )
    if sample_col is None:
        raise ValueError(f"No sample ID column found. Available: {list(df.columns)}")

    # Identify ground-truth columns
    nmajor_col = next((c for c in ('nMajor', 'nMajor_true') if c in df.columns), None)
    nminor_col = next((c for c in ('nMinor', 'nMinor_true') if c in df.columns), None)

    if nmajor_col is None or nminor_col is None:
        raise ValueError("Cannot find nMajor / nMinor columns for ASCAT ground truth.")

    # Keep only rows with ASCAT ground truth
    has_gt = df[nmajor_col].notna() & df[nminor_col].notna()
    ascat_samples = sorted(df.loc[has_gt, sample_col].unique())
    print(f"  Unique ASCAT-profiled samples: {len(ascat_samples):,}")

    if len(ascat_samples) == 0:
        raise ValueError("No ASCAT-profiled samples found. Check nMajor/nMinor columns.")

    # Deterministic shuffle and split
    rng = np.random.default_rng(RANDOM_STATE)
    shuffled = np.array(ascat_samples)
    rng.shuffle(shuffled)

    n_cal = int(np.floor(len(shuffled) * CAL_FRAC))
    cal_samples = sorted(shuffled[:n_cal].tolist())
    val_samples = sorted(shuffled[n_cal:].tolist())

    print(f"\nSplit (random_state={RANDOM_STATE}, cal_frac={CAL_FRAC}):")
    print(f"  Calibration : {len(cal_samples):,} samples  ({len(cal_samples)/len(ascat_samples):.1%})")
    print(f"  Validation  : {len(val_samples):,} samples  ({len(val_samples)/len(ascat_samples):.1%})")

    # Sanity check: no overlap
    overlap = set(cal_samples) & set(val_samples)
    assert len(overlap) == 0, f"Overlap detected: {overlap}"

    # Write output files
    os.makedirs(OUT_DIR, exist_ok=True)
    cal_file = os.path.join(OUT_DIR, "calibration_samples.txt")
    val_file = os.path.join(OUT_DIR, "validation_samples.txt")

    with open(cal_file, "w") as f:
        f.write("# Calibration samples (80%) — used by calibrate_thresholds.py\n")
        f.write("# Generated by split_samples.py  random_state=42\n")
        f.write("\n".join(cal_samples) + "\n")

    with open(val_file, "w") as f:
        f.write("# Validation samples (20%) — used by autoresearch_baf_hrd/prepare.py\n")
        f.write("# Generated by split_samples.py  random_state=42\n")
        f.write("\n".join(val_samples) + "\n")

    print(f"\n✓ Written: {cal_file}")
    print(f"✓ Written: {val_file}")
    print("\nNext steps:")
    print("  1. Set PARAMS['calibration_samples_file'] in calibrate_thresholds.py")
    print("     → run_recalibrate.sbatch")
    print("  2. Set VALIDATION_SAMPLES_FILE in autoresearch_baf_hrd/prepare.py")
    print("     → autoresearch_baf_hrd/run_prepare.sbatch")
    print("  3. Re-run autoresearch_baf_hrd/run_experiment.sbatch for honest baseline")


if __name__ == "__main__":
    main()
